from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


DECODER_LAYER_NUM = 16
MAX_PRE_SEQ_LEN = 1024
MAX_DEC_SEQ_LEN = 1024
MAX_SUM_SEQ_LEN = MAX_PRE_SEQ_LEN + MAX_DEC_SEQ_LEN

HIDDEN_DIM = 2048
KV_HIDDEN_DIM = 512
HEAD_DIM = 64
KV_HEAD_NUM = KV_HIDDEN_DIM // HEAD_DIM
INTER_DIM = 8192
VOCAB_SIZE = 128256

TOKEN_PARALLEL = 8
PRE_QKVO_W_PARALLEL = 24
PRE_QKVO_W_PARALLEL_READ = 32
PRE_K_PARALLEL = 16
PRE_V_PARALLEL = 16
PRE_FFN_W_PARALLEL = 96
PRE_FFN_W_BLOCK_NUM = 3
PRE_FFN_W_PARALLEL_READ = 96

PREF_QKVO_W_PARALLEL = PRE_QKVO_W_PARALLEL
PREF_QKVO_W_PARALLEL_READ = PRE_QKVO_W_PARALLEL_READ
PREF_K_PARALLEL = PRE_K_PARALLEL
PREF_V_PARALLEL = PRE_V_PARALLEL
PREF_FFN_W_PARALLEL = PRE_FFN_W_PARALLEL
PREF_FFN_W_BLOCK_NUM = PRE_FFN_W_BLOCK_NUM
PREF_FFN_W_PARALLEL_READ = PRE_FFN_W_PARALLEL_READ

T_BLOCK_PARALLEL = 8
T_QKVO_FFN_BLOCK_PARALLEL = 16
DEC_HEAD_PARALLEL = T_QKVO_FFN_BLOCK_PARALLEL // 2
DEC_QKVO_FFN_W_PARALLEL = 64
DEC_K_PARALLEL = DEC_QKVO_FFN_W_PARALLEL // 2
DEC_V_PARALLEL = DEC_QKVO_FFN_W_PARALLEL // 2

KV_HIDDEN_DIM_PAD = max(T_QKVO_FFN_BLOCK_PARALLEL * DEC_QKVO_FFN_W_PARALLEL, 2 * KV_HIDDEN_DIM)
VOCAB_SIZE_PAD = 131072

PREF_IO_ELEMS = (DECODER_LAYER_NUM + 1) * MAX_PRE_SEQ_LEN // TOKEN_PARALLEL * HIDDEN_DIM
PREF_QKVO_ELEMS = (
    DECODER_LAYER_NUM
    * (
        (KV_HIDDEN_DIM + PRE_QKVO_W_PARALLEL - 1) // PRE_QKVO_W_PARALLEL
        + (HIDDEN_DIM + PRE_QKVO_W_PARALLEL - 1) // PRE_QKVO_W_PARALLEL
    )
    * HIDDEN_DIM
)
PREF_QKVO_S_ELEMS = DECODER_LAYER_NUM * (KV_HIDDEN_DIM + HIDDEN_DIM)
PREF_K_CACHE_ELEMS = DECODER_LAYER_NUM * KV_HEAD_NUM * MAX_PRE_SEQ_LEN // PRE_K_PARALLEL * HEAD_DIM
PREF_V_CACHE_ELEMS = DECODER_LAYER_NUM * KV_HIDDEN_DIM // PRE_V_PARALLEL * MAX_PRE_SEQ_LEN
PREF_FFN_INTER_ELEMS = (
    DECODER_LAYER_NUM
    * ((INTER_DIM + PRE_FFN_W_PARALLEL - 1) // PRE_FFN_W_PARALLEL)
    * HIDDEN_DIM
)
PREF_FFN_DOWN_ELEMS = (
    DECODER_LAYER_NUM
    * ((HIDDEN_DIM + PRE_FFN_W_PARALLEL - 1) // PRE_FFN_W_PARALLEL)
    * INTER_DIM
)

W_KV_ADDR_BIAS = 0
W_Q_ADDR_BIAS = (
    W_KV_ADDR_BIAS
    + DECODER_LAYER_NUM * KV_HIDDEN_DIM_PAD // (T_QKVO_FFN_BLOCK_PARALLEL * DEC_QKVO_FFN_W_PARALLEL) * HIDDEN_DIM
)
W_O_ADDR_BIAS = (
    W_Q_ADDR_BIAS
    + DECODER_LAYER_NUM * HIDDEN_DIM // (T_QKVO_FFN_BLOCK_PARALLEL * DEC_QKVO_FFN_W_PARALLEL) * HIDDEN_DIM
)
W_FFN_UP_ADDR_BIAS = (
    W_O_ADDR_BIAS
    + DECODER_LAYER_NUM * HIDDEN_DIM // (T_QKVO_FFN_BLOCK_PARALLEL * DEC_QKVO_FFN_W_PARALLEL) * HIDDEN_DIM
)
W_FFN_GATE_ADDR_BIAS = (
    W_FFN_UP_ADDR_BIAS
    + DECODER_LAYER_NUM * INTER_DIM // (T_QKVO_FFN_BLOCK_PARALLEL * DEC_QKVO_FFN_W_PARALLEL) * HIDDEN_DIM
)
W_FFN_DOWN_ADDR_BIAS = (
    W_FFN_GATE_ADDR_BIAS
    + DECODER_LAYER_NUM * INTER_DIM // (T_QKVO_FFN_BLOCK_PARALLEL * DEC_QKVO_FFN_W_PARALLEL) * HIDDEN_DIM
)
W_VOCAB_ADDR_BIAS = (
    W_FFN_DOWN_ADDR_BIAS
    + DECODER_LAYER_NUM * HIDDEN_DIM // (T_QKVO_FFN_BLOCK_PARALLEL * DEC_QKVO_FFN_W_PARALLEL) * INTER_DIM
)
W_QKVO_FFN_SIZE = (
    W_VOCAB_ADDR_BIAS
    + VOCAB_SIZE_PAD // (T_QKVO_FFN_BLOCK_PARALLEL * DEC_QKVO_FFN_W_PARALLEL) * HIDDEN_DIM
)

W_S_KV_ADDR_BIAS = 0
W_S_Q_ADDR_BIAS = W_S_KV_ADDR_BIAS + DECODER_LAYER_NUM * KV_HIDDEN_DIM_PAD
W_S_O_ADDR_BIAS = W_S_Q_ADDR_BIAS + DECODER_LAYER_NUM * HIDDEN_DIM
W_S_FFN_UP_ADDR_BIAS = W_S_O_ADDR_BIAS + DECODER_LAYER_NUM * HIDDEN_DIM
W_S_FFN_GATE_ADDR_BIAS = W_S_FFN_UP_ADDR_BIAS + DECODER_LAYER_NUM * INTER_DIM
W_S_FFN_DOWN_ADDR_BIAS = W_S_FFN_GATE_ADDR_BIAS + DECODER_LAYER_NUM * INTER_DIM
W_S_VOCAB_ADDR_BIAS = W_S_FFN_DOWN_ADDR_BIAS + DECODER_LAYER_NUM * HIDDEN_DIM
W_S_QKVO_FFN_SIZE = W_S_VOCAB_ADDR_BIAS + VOCAB_SIZE_PAD

DEC_K_CACHE_ELEMS = (
    DECODER_LAYER_NUM * KV_HEAD_NUM // DEC_HEAD_PARALLEL * MAX_SUM_SEQ_LEN // DEC_K_PARALLEL * HEAD_DIM
)
DEC_V_CACHE_ELEMS = (
    DECODER_LAYER_NUM * (KV_HEAD_NUM // DEC_HEAD_PARALLEL * HEAD_DIM // DEC_V_PARALLEL) * MAX_SUM_SEQ_LEN
)


@dataclass(frozen=True)
class U280Paths:
    model_dir: Path
    parameters_dir: Path
    prefill_xclbin: Path
    decode_xclbin: Path

    @classmethod
    def default(cls) -> "U280Paths":
        repo_root = Path(__file__).resolve().parents[1]
        model_dir = repo_root / "SpinQuant_Llama_32_1B_Ins"
        run_dir = model_dir / "run"
        return cls(
            model_dir=model_dir,
            parameters_dir=model_dir / "parameters",
            prefill_xclbin=run_dir
            / "bitstreams"
            / "SpinQuant_Prefilling_mem_opt_xilinx_u280_gen3x16_xdma_1_202211_1.xclbin",
            decode_xclbin=run_dir
            / "bitstreams"
            / "SpinQuant_Decoding_mem_opt_xilinx_u280_gen3x16_xdma_1_202211_1.xclbin",
        )
